dataset:
  name: PhysioDataset
  location: ../data/physionet/physionet.org/files/eegmmidb/1.0.0
  preprocess: false

model:
  name: CNN_LSTM

optimizer:
  initial_lr: 0.0001
  weight_decay: 0.01

channel:
  number: 64
  select: false

transform:
  name: Normal

train:
  subject: 1
  batch_size: 8
  epochs: 300
  trained_model_path: ../trained/

evaluate:
  batch_size: 8
