dataset:
  name: PhysioDataset
  location: ../data/physionet/physionet.org/files/eegmmidb/1.0.0
  preprocess: false

model:
  name: CSP_LDA

channel:
  number: 32
  select: true

transform:
  name: AlphaBeta

train:
  subject: 10
  batch_size: all

evaluate:
  batch_size: all
