dataset:
  name: PhysioDataset
  location: ../data/physionet/physionet.org/files/eegmmidb/1.0.0
  preprocess: false

model:
  name: NeuralNetwork

channel:
  number: 64
  select: false

transform:
  name: Energy_Wavelet

train:
  subject: 1
  batch_size: all

evaluate:
  batch_size: all
