dataset:
  name: PhysioDataset
  location: ../data/physionet/physionet.org/files/eegmmidb/1.0.0
  preprocess: false

model:
  name: MIN2Net

channel:
  number: 64
  select: false

transform:
  name: AlphaBeta

train:
  subject: 3
  batch_size: all

evaluate:
  batch_size: all
