dataset:
  name: PhysioDataset
  location: ../data/physionet/physionet.org/files/eegmmidb/1.0.0
  preprocess: false

model:
  name: SVM

channel:
  number: 64
  select: false

transform:
  name: filter_msd

train:
  subject: 10
  batch_size: all

evaluate:
  batch_size: all
